#!/bin/bash

# set -euo pipefail

TEST_RESULTS_PATH="${BUILDKITE_PLUGIN_TEST_ANALYTICS_FROM_FILE_TEST_RESULTS_PATH}"
TEST_RESULTS_FORMAT="${BUILDKITE_PLUGIN_TEST_ANALYTICS_FROM_FILE_TEST_RESULTS_FORMAT}"
TEST_RUN_LINK="${BUILDKITE_PLUGIN_TEST_ANALYTICS_FROM_FILE_TEST_RUN_LINK:-false}"
CONTEXT="${BUILDKITE_PLUGIN_TEST_ANALYTICS_FROM_FILE_ANNOTATION_CONTEXT:-bkta}"
STYLE="${BUILDKITE_PLUGIN_TEST_ANALYTICS_FROM_FILE_ANNOTATION_STYLE:-info}"
APPEND_FLAG="${BUILDKITE_PLUGIN_TEST_ANALYTICS_FROM_FILE_ANNOTATION_APPEND:-false}"

bk_annotate_test_analytic_link(){
  echo "--- :spiral_note_pad: Annotate Test Analytics link"
  test_analytics_run_url=$(echo "$1" | grep -o '"run_url": *"[^"]*"' | cut -d'"' -f4)
  echo "Test Analytic url: ${test_analytics_run_url}"

  ANNOTATION="
<p>See <a href=\"$test_analytics_run_url\">the global test run</a> for more information.</p>
<p>The test run includes results from <a href=\"$BUILDKITE_JOB_URL\">global run job</a></p>
"
  buildkite-agent annotate "$ANNOTATION" --style "$STYLE" --context "$CONTEXT" $APPEND_FLAG
}


if [[ -n "$BUILDKITE_ANALYTICS_TOKEN" ]]; then
  echo "Missing Buildkite Test Analytic Token at BUILDKITE_ANALYTICS_TOKEN env variable"
  exit 1
fi

if [[ -n "$TEST_RESULTS_PATH" ]]; then
  echo "'TEST_RESULTS_PATH' not received"
  exit 1
fi

if [[ ! $TEST_RESULTS_FORMAT =~ ^(json|junit)$ ]]; then
  echo "'$TEST_RESULTS_FORMAT' is a non valid format <json | junit>."
  exit 1
fi

if [[ ! $TEST_RUN_LINK =~ ^(true|false)$ ]]; then
  echo "'$TEST_RUN_LINK' is a non valid format <true | false"
  exit 1
fi

BK_RUN="${BUILDKITE_TRIGGERED_FROM_BUILD_PIPELINE_SLUG:-BUILDKITE_PIPELINE_SLUG}_${BUILDKITE_TRIGGERED_FROM_BUILD_NUMBER:-BUILDKITE_BUILD_NUMBER}"

test_analytics_response=$(curl -X POST \
  -H "Authorization: Token token=\"${BK_TEST_ANALYTIC_TOKEN}\"" \
  -F "data=@$TEST_RESULTS_PATH" \
  -F "format=$TEST_RESULTS_FORMAT" \
  -F "run_env[CI]=buildkite" \
  -F "run_env[key]=${BUILDKITE_TRIGGERED_FROM_BUILD_ID:-$BUILDKITE_BUILD_ID}" \
  -F "run_env[url]=$BUILDKITE_JOB_URL" \
  -F "run_env[branch]=$BUILDKITE_BRANCH" \
  -F "run_env[commit_sha]=$BUILDKITE_COMMIT" \
  -F "run_env[number]=${BUILDKITE_TRIGGERED_FROM_BUILD_NUMBER:-$BUILDKITE_BUILD_NUMBER}" \
  -F "run_env[job_id]=$BUILDKITE_JOB_ID" \
  -F "run_env[message]=$BK_RUN" \
  https://analytics-api.buildkite.com/v1/uploads
)

[[ "$TEST_RUN_LINK" == "true" ]] && bk_annotate_test_analytic_link "$test_analytics_response"

echo "Test results sent to Buildkite Test Analytics - Done"
